config/routes.rb
TMS::Application.routes.draw do
  resources :task_types

  resources :activities

  resources :tasks

  devise_for :users

  resources :users

  resources :departments
  resources :roles
  resources :organizations

  
  root :controller=>'passthrough', :action => 'index'
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  match 'get_departments', :controller=>'users', :action => 'get_departments'
  match 'overview', :controller=>'overview', :action => 'overview', :as => "overview"
  match 'overview/load_tasks', :controller=>'overview', :action => 'load_tasks', :as => "load_tasks"
  match 'overview/load_task_info', :controller=>'overview', :action => 'load_task_info', :as => "load_task_info"
  match 'overview/load_task_fill_form', :controller=>'overview', :action => 'load_task_fill_form', :as => "load_task_fill_form"
  match 'overview/load_summary', :controller=>'overview', :action => 'load_summary', :as => "load_summary"
  match 'report', :controller=>'report', :action => 'index', :as => "report"
  match 'tasks/assign_task/:task_id', :controller=>'tasks', :action => 'assign', :as => "assign_task"
  match 'tasks/save_assign', :controller=>'tasks', :action => 'save_assign', :as => "save_assign"
  match 'overview_department', :controller=>'overview', :action => 'overview_department', :as => "overview_department"
  match 'overview_staff', :controller=>'overview', :action => 'overview_staff', :as => "overview_staff"
  match 'log_time', :controller=>'overview', :action=>'log_time', :as => 'log_time'
  match 'report/post', :controller=>'report', :action=>'post', :as => 'report_csv'
  match 'report/error', :controller=>'report', :action=>'error'
end

app/controllers/task_types_controller.rb
class TaskTypesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_page_name
  
  load_and_authorize_resource :only => [:show,:index,:new,:destroy,:edit,:create ,:update]
  
  
  # GET /task_types
  # GET /task_types.json
  def index
    @task_types = TaskType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @task_types }
    end
  end

  # GET /task_types/1
  # GET /task_types/1.json
  def show
    @task_type = TaskType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task_type }
    end
  end

  # GET /task_types/new
  # GET /task_types/new.json
  def new
    @task_type = TaskType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task_type }
    end
  end

  # GET /task_types/1/edit
  def edit
    @task_type = TaskType.find(params[:id])
  end

  # POST /task_types
  # POST /task_types.json
  def create
    @task_type = TaskType.new(params[:task_type])

    respond_to do |format|
      if @task_type.save
        format.html { redirect_to @task_type, notice: 'Task type was successfully created.' }
        format.json { render json: @task_type, status: :created, location: @task_type }
      else
        format.html { render action: "new" }
        format.json { render json: @task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /task_types/1
  # PUT /task_types/1.json
  def update
    @task_type = TaskType.find(params[:id])

    respond_to do |format|
      if @task_type.update_attributes(params[:task_type])
        format.html { redirect_to @task_type, notice: 'Task type was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_types/1
  # DELETE /task_types/1.json
  def destroy
    @task_type = TaskType.find(params[:id])
    if @task_type.destroy

      respond_to do |format|
        format.html { redirect_to task_types_url }
        format.json { head :ok }
      end
    else
      error_list = ''
      @task_type.errors.full_messages.each do |msg|
        error_list << msg
      end

      respond_to do |format|
        format.html { redirect_to task_types_url, :alert=>error_list }
        format.json { head :error }
      end
    end
      
  end
  
  def set_page_name
    @page_name = "task_types"
  end
end

app/helpers/task_types_helper.rb
module TaskTypesHelper
end

app/views/task_types/_form.html.erb
<%= form_for(@task_type) do |f| %>
<% if @task_type.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@task_type.errors.count, "error") %> prohibited this task type from being saved:</h2>
	<ul>
		<% @task_type.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>


<fieldset class="fields_edit">
	<ol>
		<li>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</li>
	</ol>
</fieldset>

<div class="actions">
	<%= f.submit %>
</div>
<% end %> 

app/views/task_types/edit.html.erb
<div>
	<h3 class="show_panel_title">Edit Task Type</h3>
	<%= link_to image_tag("search.png", :border => 0, :title => 'View'), @task_type, :class=>"link_image" %>
	<%= link_to image_tag("back.png", :border => 0, :title => 'Back') , task_types_path, :class=>"link_image" %>
	<div style="clear:both"></div>
</div>
<%= render 'form' %> 

app/views/task_types/index.html.erb
<div>
	<h3 class="title_panel">List of Task Types</h3>
	<%= link_to image_tag("add.png", :border => 0, :title => 'New'),  new_task_type_path, :class=>"link_image" %>
</div>
<table class="table_index">
	<tr>
		<th>Name</th>
		<th class="actions_title">Actions</th>
	</tr>
	<% @task_types.each do |task_type| %>
	<tr class="<%= cycle("odd", "even") %>">
		<td><%= task_type.name %></td>
		<td><%= link_to image_tag("search.png", :border => 0, :title => 'View'), task_type, :class=>"actions_table" %>
		<%= link_to image_tag("edit.png", :border => 0, :title => 'Edit'), edit_task_type_path(task_type), :class=>"actions_table" %>
		<%= link_to image_tag("remove.png", :border => 0, :title => 'Delete'), task_type, confirm: 'Are you sure that you want to delete?', method: :delete, :class=>"actions_table" %> </td>
	</tr>
	<% end %>
</table>
<br />

app/views/task_types/new.html.erb
<div>
<h3 class="show_panel_title">New Task Type</h3>
<%= link_to image_tag("back.png", :border => 0, :title => 'Back') , task_types_path, :class=>"link_image" %>
<div style="clear:both"></div>
</div>
<%= render 'form' %>

app/views/task_types/show.html.erb
<div class="show_panel">
	<h3 class="show_panel_title">Task Type details</h3>
	<%= link_to image_tag("edit.png", :border => 0, :title => 'Edit'), edit_task_type_path(@task_type), :class=>"link_image" %>
	<%= link_to image_tag("back.png", :border => 0, :title => 'Back') , task_types_path, :class=>"link_image" %>
	<div style="clear:both"></div>
	<div class="show_panel_contents">
		<table>
			<tr>
				<th>Name:</th>
				<td><%= @task_type.name %></td>
			</tr>
		</table>
	</div>
</div>