config/routes.rb
TMS::Application.routes.draw do
  resources :task_types

  resources :activities

  resources :tasks

  devise_for :users

  resources :users

  resources :departments
  resources :roles
  resources :organizations

  
  root :controller=>'passthrough', :action => 'index'
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  match 'get_departments', :controller=>'users', :action => 'get_departments'
  match 'overview', :controller=>'overview', :action => 'overview', :as => "overview"
  match 'overview/load_tasks', :controller=>'overview', :action => 'load_tasks', :as => "load_tasks"
  match 'overview/load_task_info', :controller=>'overview', :action => 'load_task_info', :as => "load_task_info"
  match 'overview/load_task_fill_form', :controller=>'overview', :action => 'load_task_fill_form', :as => "load_task_fill_form"
  match 'overview/load_summary', :controller=>'overview', :action => 'load_summary', :as => "load_summary"
  match 'report', :controller=>'report', :action => 'index', :as => "report"
  match 'tasks/assign_task/:task_id', :controller=>'tasks', :action => 'assign', :as => "assign_task"
  match 'tasks/save_assign', :controller=>'tasks', :action => 'save_assign', :as => "save_assign"
  match 'overview_department', :controller=>'overview', :action => 'overview_department', :as => "overview_department"
  match 'overview_staff', :controller=>'overview', :action => 'overview_staff', :as => "overview_staff"
  match 'log_time', :controller=>'overview', :action=>'log_time', :as => 'log_time'
  match 'report/post', :controller=>'report', :action=>'post', :as => 'report_csv'
  match 'report/error', :controller=>'report', :action=>'error'
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id            :integer         not null, primary key
#  name          :string(255)
#  description   :text
#  max_time      :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#  department_id :integer
#  task_type_id  :integer
#

class Task < ActiveRecord::Base
  
  validates_presence_of :name
  validates_presence_of :task_type_id
  validates_presence_of :department
  belongs_to :department
  belongs_to :task_type
  has_many :activities, :dependent => :destroy
  has_many :assignations, :dependent => :destroy
  has_many :users, :through => :assignations
  has_many :daily_tasks, :dependent => :destroy
  
  
  # gets the state of the task for the user
  # 1 -> Not started
  # 2 -> Started
  # 3 -> Stopped
  def get_state(user_id, date=Date.today)
    dt = DailyTask.find(:first, :conditions => { :user_id => user_id, :task_id => self.id, :date=> date })
    
    if dt.nil?
      return 1
    else
      puts "WILL REUTURN" + dt.to_json
      if dt.state.nil?
        return 1
      else
        dt.state  
      end
    end
  end
  
  def max_time_in_seconds
    if self.max_time.nil?
      return 0
    else
      time_splitted = self.max_time.split(':')
      if time_splitted.size == 1
        return time_splitted[0].to_i * 3600
      else
        if time_splitted.size == 2
          return time_splitted[0].to_i * 3600 + time_splitted[1].to_i * 60
        else
          return 0
        end
      end
    end
  end
  
  def to_s
    self.name
  end
end

app/models/task_type.rb
# == Schema Information
#
# Table name: task_types
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class TaskType < ActiveRecord::Base
  validates_presence_of :name
  has_many :tasks
  before_destroy :without_tasks
  
  def to_s
    return self.name
  end
  
  def without_tasks

    if self.tasks.size() > 0
      self.errors.add :base, "The task type cannot be deleted because it has tasks associated to it."
    end

    self.errors.blank?
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_page_name
  
  load_and_authorize_resource :only => [:show,:index,:new,:destroy,:edit,:create ,:update, :assign, :save_assign]
  
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.find(:all, :conditions=>{:department_id => current_user.department.id})

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])
    # ajax_flag = params[:ajax_flag]
    @task.department = Department.find(current_user.department.id)
    
    if request.xhr?
      
      if @task.save
        tasks = Task.find(:all, :conditions => {:department_id => current_user.department.id})
        task_list = render_to_string :partial => 'tasks', :locals => {:tasks => tasks}
        task_list =  task_list.html_safe.gsub(/\n/, '').gsub(/\t/, '').gsub(/\r/, '')
        render :json => {:html => task_list, :error => ''}
      else
        redraw_partial = render_to_string :action => 'new.html.erb', :layout => false
        redraw_partial = redraw_partial.html_safe.gsub(/\n/, '').gsub(/\t/, '').gsub(/\r/, '')
        render :json => {:html => redraw_partial, :error => 'Error'}
      end
    else
      respond_to do |format|
        if @task.save
              format.html { redirect_to @task, notice: 'Task was successfully created.' }
              format.json { render json: @task, status: :created, location: @task }  
        else
          format.html { render action: "new" }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end
    
      
    # else
      # if @task.save
        # render :json => {:status => "Error"}
        # # render :partial => 'tasks', :locals => {:tasks => current_user.department.tasks}
      # else
        # render :json => {:status => "Error"}
      # end
    # end
      
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :ok }
    end
  end
  
  def set_page_name
    @page_name = "tasks"
  end
  
  def assign
    task_id = params[:task_id]
    @task = Task.find(task_id)
    @users = User.find(:all, :conditions => {:department_id => current_user.department.id}).select{|user| user.role? :staff}
    respond_to do |format|
      format.html # assign.html.erb
    end
  end
  
  def save_assign
    task_id = params[:task_id]
    params[:user_assigns] ||= []
    assigns = params[:user_assigns]
    
    if !task_id.nil?
      Assignation.delete_all(["task_id = ?", task_id])
    
      assigns.each do |assign|
        user = User.find(assign)
        if (!user.nil?)
          assignment = Assignation.new
          assignment.user_id = user.id
          assignment.task_id = task_id
          assignment.save
        end
      end
      
    end
    
    flash.now[:notice] = "The selected users have been assigned"
    
    @tasks = Task.find(:all, :conditions=>{:department_id => current_user.department.id})
    respond_to do |format|
      format.html { render action: "index" }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def form_or_remote_form object, *opts, &proc
    if request.xhr?
      form_for object, {:remote => true}, &proc
    else
      
      form_for object, *opts, &proc
    end
  end
end

app/views/tasks/_fill_task_form.html.erb
<%= form_tag @base_url + '/log_time', :id=>'form_fill_task', :remote=>true do %>
	<%= hidden_field_tag 'task_id', @task.id.to_s %>
	<fieldset class="fields_edit">
		<ol>
			<li>
				<%= label_tag 'Summary' %>
				<%= text_area_tag :summary, @daily_task.summary %>
			</li>
			<li>
				<%= label_tag 'Quantity' %>
				<%= text_field_tag :ammount, @daily_task.ammount %>
			</li>
		</ol>
		<div id="actions_staff">
			<% state= @task.get_state(@current_user.id)%>
			<% if state == 2 %>
				<%= image_submit_tag "stop.png", :class=> 'play_pause_stop_buttons', :title=>'Stop', :name=>'Stop'%>
			<% else%>
				<%= image_submit_tag "play.png", :class=> 'play_pause_stop_buttons', :title=> 'Start', :name=>'Start'%>
			<% end %>
		</div>
		<div class="actions" id="actions_staff">
			<%= submit_tag "Store info"%>	
		</div>
	</fieldset>
	
	
<% end %>

app/views/tasks/_form.html.erb
<%= form_or_remote_form(@task) do |f| %>


<% if @task.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@task.errors.count, "error") %> prohibited this organization from being saved:</h2>
	<ul>
		<% @task.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>


<fieldset class="fields_edit">
	<ol>
		<li>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</li>
		<li>
			<%= f.label :description %>
			<%= f.text_field :description %>
		</li>
		<li>
			<%= f.label :max_time %>

			<%= f.text_field :max_time, :class=>'spin_input' %>
				
		</li>
		<li>
			<%= f.label :task_type %>
			<%= f.collection_select :task_type_id, TaskType.find(:all), :id, :name %>

		</li>
	</ol>
</fieldset>

<div class="actions">
	<%= f.submit %>
</div>
<% end %> 

app/views/tasks/_overview_task_summary.html.erb
SUMMARY

app/views/tasks/_overview_tasks.html.erb
<table class="table_overview <%= table_class %>">

	<% @tasks.each do |task| %>
	<tr class="<%= cycle("odd", "even") %>">
		<td>
				<%=hidden_field_tag 'user_id', user_id.to_s %>
			
			<%=hidden_field_tag 'task_id', task.id.to_s %><%= task.name %></td>
	</tr>
	<% end %>
</table>
<br />

app/views/tasks/_task_summary.html.erb
<div class="section_summary">
	<%= label_tag 'State: ', nil, :class=>'label_summary'%>
	<% state= @task.get_state(user_id)%>
	<% if state == 1 %>
		Not started
	<% else %>
		<% if state == 2%>
			In progress
		<% else %>
			<% if state == 3%>
				Finished
			<%else%>	
				Not determined
			<%end%>
		<%end%>
	<%end%>
</div>

<div class="section_summary">
	<%= label_tag 'Description: ', nil, :class=>'label_summary'%>
	 <%= @task.description%>
</div>

<div class="section_summary">
	<%= label_tag 'Maximum time: ', nil, :class=>'label_summary'%>
	 <%= @task.max_time%>
</div>


<div class="section_summary">
	<% if @task.activities.size > 0 %>
	<%= label_tag 'Activities:', nil, :class=>'label_summary'%>
	
	<div id="summary_table_wrapper">
		<table class="table_index">
			<tr>
				<th>Name</th>
				<th>Description</th>
			</tr>
			<% @task.activities.each do |activity|%>
			<tr class="<%= cycle("odd", "even") %>">
				<td><%= activity.name %></td>
				<td><%= activity.description %></td>
			</tr>
			<% end %>
		</table>
	</div>
	<% end %>
</div>

<% if !@daily_task.nil?%>
	<% if @daily_task.time_logs.size > 0 %>
	<div class="section_summary">
		<%= label_tag 'Total time spent today (hh:mm:ss): ', nil, :class=>'label_summary'%>
		<%= @daily_task.total_time_formatted%>
		<% if @daily_task.total_time > @task.max_time_in_seconds %>
			<span class="warning_summary_label"> (exceeded)</span>
		<%end%>
	</div>
	
	
	<div class="section_summary">
		<%= label_tag 'Today time logs:', nil, :class=>'label_summary'%>
		
		<div id="summary_table_wrapper">
			<table class="table_index">
				<tr>
					<th>Start time</th>
					<th>End time</th>
				</tr>
				<% @daily_task.time_logs.each do |time_log|%>
				<tr class="<%= cycle("odd", "even") %>">
					<td><%= time_log.start_time.to_formatted_s(:long) unless time_log.start_time.nil? %></td>
					<td><%= time_log.end_time.to_formatted_s(:long) unless time_log.end_time.nil? %></td>
				</tr>
				<% end %>
			</table>
		</div>
		
	</div>
	
	
	<% end %>
<% end%>

app/views/tasks/_tasks.html.erb
<%= collection_select :activity, :task_id, tasks, :id, :name %>

app/views/tasks/assign.html.erb
<%= form_tag save_assign_url, :method => :post do %>
<%= hidden_field_tag(:task_id, @task.id) %>
<div id="table_wrapper_popup">
	<table class="table_index">
		<tr>
			<th></th>
			<th>Name</th>
			<th>Position</th>
		</tr>
		<% @users.each do |user| %>
		<tr class="<%= cycle("odd", "even") %>">
			<td><%= check_box_tag 'user_assigns[]', user.id, user.tasks.include?(@task) %></td>

			<td><%= user.name %></td>
			<td><%= user.position %></td>
		</tr>
		<% end %>
	</table>
</div>
<div class="actions">
	<%=submit_tag%>
</div>
<%end%>

app/views/tasks/edit.html.erb
<div>
	<h3 class="show_panel_title">Edit Task</h3>
	<%= link_to image_tag("search.png", :border => 0, :title => 'View'), @task, :class=>"link_image" %>
	<%= link_to image_tag("back.png", :border => 0, :title => 'Back') , tasks_path, :class=>"link_image" %>
	<div style="clear:both"></div>
</div>
<%= render 'form' %> 

app/views/tasks/index.html.erb
<div id="modal-container"></div>
<div id="modal">
	<%= link_to image_tag("delete.png", :border => 0, :title => 'Close'),  "#", :class=>"close", :remote => true  %>
</div>

<% content_for :javascript_includes do %>
  <%= javascript_include_tag "popup_assign" %>
<% end %>

<div>
	<h3 class="title_panel">List of Tasks</h3>
	<%= link_to image_tag("add.png", :border => 0, :title => 'New'),  new_task_path, :class=>"link_image" %>
</div>
<table class="table_index">
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Max. time</th>
		<th>Task type</th>
		<th class="actions_title">Actions</th>
	</tr>
	<% @tasks.each do |task| %>
	<tr class="<%= cycle("odd", "even") %>">
		<td><%= task.name %></td>
		<td><%= task.description %></td>
		<td><%= task.max_time %></td>
		<td><%= task.task_type %></td>
		<td><%= link_to image_tag("search.png", :border => 0, :title => 'View'), task, :class=>"actions_table" %>
		<%= link_to image_tag("edit.png", :border => 0, :title => 'Edit'), edit_task_path(task), :class=>"actions_table" %>
		<%= link_to image_tag("remove.png", :border => 0, :title => 'Delete'), task, confirm: 'Are you sure that you want to delete?', method: :delete, :class=>"actions_table" %> 
		<%= link_to image_tag("assign.png", :border => 0, :title => 'Assign'), assign_task_path(task.id), :class=>"actions_table", :remote=>"true" %></td>
	</tr>
	<% end %>
</table>
<br />

app/views/tasks/new.html.erb
<div>
<h3 class="show_panel_title">New Task</h3>
<% if !request.xhr? %>
<!-- Back link just if request wasnt ajax -->
  <%= link_to image_tag("back.png", :border => 0, :title => 'Back') , tasks_path, :class=>"link_image" %>
<%end%>

<div style="clear:both"></div>
</div>
<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="show_panel">
	<h3 class="show_panel_title">Task details</h3>
	<%= link_to image_tag("edit.png", :border => 0, :title => 'Edit'), edit_task_path(@task), :class=>"link_image" %>
	<%= link_to image_tag("back.png", :border => 0, :title => 'Back') , tasks_path, :class=>"link_image" %>
	<div style="clear:both"></div>
	<div class="show_panel_contents">
		<table>
			<tr>
				<th>Name:</th>
				<td><%= @task.name %></td>
			</tr>
			<tr>
				<th>Description:</th>
				<td><%= @task.description %></td>
			</tr>
			<tr>
				<th>Max. time:</th>
				<td><%= @task.max_time %></td>
			</tr>
			<tr>
				<th>Task type:</th>
				<td><%= @task.task_type %></td>
			</tr>
		</table>
	</div>
</div>