config/routes.rb
TMS::Application.routes.draw do
  resources :task_types

  resources :activities

  resources :tasks

  devise_for :users

  resources :users

  resources :departments
  resources :roles
  resources :organizations

  
  root :controller=>'passthrough', :action => 'index'
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  match 'get_departments', :controller=>'users', :action => 'get_departments'
  match 'overview', :controller=>'overview', :action => 'overview', :as => "overview"
  match 'overview/load_tasks', :controller=>'overview', :action => 'load_tasks', :as => "load_tasks"
  match 'overview/load_task_info', :controller=>'overview', :action => 'load_task_info', :as => "load_task_info"
  match 'overview/load_task_fill_form', :controller=>'overview', :action => 'load_task_fill_form', :as => "load_task_fill_form"
  match 'overview/load_summary', :controller=>'overview', :action => 'load_summary', :as => "load_summary"
  match 'report', :controller=>'report', :action => 'index', :as => "report"
  match 'tasks/assign_task/:task_id', :controller=>'tasks', :action => 'assign', :as => "assign_task"
  match 'tasks/save_assign', :controller=>'tasks', :action => 'save_assign', :as => "save_assign"
  match 'overview_department', :controller=>'overview', :action => 'overview_department', :as => "overview_department"
  match 'overview_staff', :controller=>'overview', :action => 'overview_staff', :as => "overview_staff"
  match 'log_time', :controller=>'overview', :action=>'log_time', :as => 'log_time'
  match 'report/post', :controller=>'report', :action=>'post', :as => 'report_csv'
  match 'report/error', :controller=>'report', :action=>'error'
end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  description :text
#  task_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Activity < ActiveRecord::Base
  belongs_to :task
  validates_presence_of :name
  validates_presence_of :description
  validates_presence_of :task_id
  
  
  def to_s
    self.name
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_page_name
 
 
  load_and_authorize_resource :only => [:show,:index,:new,:destroy,:edit,:create ,:update]
  
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.find(:all, :joins => [:task], :conditions=>["tasks.department_id = ?", current_user.department.id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new
    @tasks = current_user.department.tasks
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
    @tasks = current_user.department.tasks
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])
    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :ok }
    end
  end
  
  def set_page_name
    @page_name = "activities"
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<div id="modal-container"></div>
<div id="modal">
	<%= link_to image_tag("delete.png", :border => 0, :title => 'Close'),  "#", :class=>"close", :remote => true  %>
</div>

<%= form_for(@activity) do |f| %>

<% content_for :javascript_includes do %>
  <%= javascript_include_tag "popup_task" %>
<% end %>


<% if @activity.errors.any? %>

<div id="error_explanation">
	<h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>
	<ul>
		<% @activity.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>


<fieldset class="fields_edit">
	<ol>
		<li>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</li>
		<li>
			<%= f.label :description %>
			<%= f.text_field :description %>
		</li>
		<li>
			<%= f.label :task %>
			<div class="activity_task_add">
			<div class="activity_task_select">
				<%= render :partial => 'tasks/tasks', :locals => {:tasks => @tasks, :f=> f}    %>
			</div>
   		 	<%= link_to image_tag("add.png", :border => 0, :title => 'New task'),  new_task_path, :class=>"task_popup", :remote => true  %>
			</div>
		</li>
		
	</ol>
</fieldset>

<div class="actions">
	<%= f.submit %>
</div>
<% end %> 

app/views/activities/edit.html.erb
<div>
	<h3 class="show_panel_title">Edit Activity</h3>
	<%= link_to image_tag("search.png", :border => 0, :title => 'View'), @activity, :class=>"link_image" %>
	<%= link_to image_tag("back.png", :border => 0, :title => 'Back') , activities_path, :class=>"link_image" %>
	<div style="clear:both"></div>
</div>
<%= render 'form' %> 

app/views/activities/index.html.erb
<div>
	<h3 class="title_panel">List of Activities</h3>
	<%= link_to image_tag("add.png", :border => 0, :title => 'New'),  new_activity_path, :class=>"link_image" %>
</div>
<table class="table_index">
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Task</th>
		<th class="actions_title">Actions</th>
	</tr>
	<% @activities.each do |activity| %>
	<tr class="<%= cycle("odd", "even") %>">
		<td><%= activity.name %></td>
		<td><%= activity.description %></td>
		<td><%= activity.task %></td>
		<td><%= link_to image_tag("search.png", :border => 0, :title => 'View'), activity, :class=>"actions_table" %>
		<%= link_to image_tag("edit.png", :border => 0, :title => 'Edit'), edit_activity_path(activity), :class=>"actions_table" %>
		<%= link_to image_tag("remove.png", :border => 0, :title => 'Delete'), activity, confirm: 'Are you sure that you want to delete?', method: :delete, :class=>"actions_table" %> </td>
	</tr>
	<% end %>
</table>
<br />

app/views/activities/new.html.erb
<div>
<h3 class="show_panel_title">New Activity</h3>
<%= link_to image_tag("back.png", :border => 0, :title => 'Back') , activities_path, :class=>"link_image" %>
<div style="clear:both"></div>
</div>
<%= render 'form' %>

app/views/activities/show.html.erb
<div class="show_panel">
	<h3 class="show_panel_title">Activity details</h3>
	<%= link_to image_tag("edit.png", :border => 0, :title => 'Edit'), edit_activity_path(@activity), :class=>"link_image" %>
	<%= link_to image_tag("back.png", :border => 0, :title => 'Back') , activities_path, :class=>"link_image" %>
	<div style="clear:both"></div>
	<div class="show_panel_contents">
		<table>
			<tr>
				<th>Name:</th>
				<td><%= @activity.name %></td>
			</tr>
			<tr>
				<th>Description:</th>
				<td><%= @activity.description %></td>
			</tr>
			<tr>
				<th>Task:</th>
				<td><%= @activity.task %></td>
			</tr>
		</table>
	</div>
</div>