config/routes.rb
TMS::Application.routes.draw do
  resources :task_types

  resources :activities

  resources :tasks

  devise_for :users

  resources :users

  resources :departments
  resources :roles
  resources :organizations

  
  root :controller=>'passthrough', :action => 'index'
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  match 'get_departments', :controller=>'users', :action => 'get_departments'
  match 'overview', :controller=>'overview', :action => 'overview', :as => "overview"
  match 'overview/load_tasks', :controller=>'overview', :action => 'load_tasks', :as => "load_tasks"
  match 'overview/load_task_info', :controller=>'overview', :action => 'load_task_info', :as => "load_task_info"
  match 'overview/load_task_fill_form', :controller=>'overview', :action => 'load_task_fill_form', :as => "load_task_fill_form"
  match 'overview/load_summary', :controller=>'overview', :action => 'load_summary', :as => "load_summary"
  match 'report', :controller=>'report', :action => 'index', :as => "report"
  match 'tasks/assign_task/:task_id', :controller=>'tasks', :action => 'assign', :as => "assign_task"
  match 'tasks/save_assign', :controller=>'tasks', :action => 'save_assign', :as => "save_assign"
  match 'overview_department', :controller=>'overview', :action => 'overview_department', :as => "overview_department"
  match 'overview_staff', :controller=>'overview', :action => 'overview_staff', :as => "overview_staff"
  match 'log_time', :controller=>'overview', :action=>'log_time', :as => 'log_time'
  match 'report/post', :controller=>'report', :action=>'post', :as => 'report_csv'
  match 'report/error', :controller=>'report', :action=>'error'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Opentask</title>
		<%= stylesheet_link_tag    "application" %>
		<%= javascript_include_tag "application" %>
		<% javascript_include_tag "users/load_departments" %> 
	
		<%= csrf_meta_tags %>
		<%= yield :head %>
	</head>

	<body class="<%= @page_name %>">
		<%=hidden_field_tag 'baseurl', @base_url %>
		<div class="body-div">
			<div id="logo_div">
				<%= link_to (image_tag ("logo_opentask.png")), root_url, :id=>"img_logo" %>
			</div>
			<!-- Select the menu based on the role -->
			<% if !@current_user.nil? %>
				<% if @current_user.role? :administrator	%>
				<div id="nav_wrap">
					<ul>
						<li class="li_overview">
							<%= link_to "Overview", overview_path %>
						</li>
						<li class="li_organization">
							<%= link_to "Organization", organizations_path %>
						</li>
						<li class="li_department">
							<%= link_to "Department", departments_path %>
						</li>
						<li class="li_user">
							<%= link_to "User", users_path %>
						</li>
					</ul>
					<%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class=>'sign_out' %>
					<%= label_tag '(' + @current_user.roles.first.name + ')', nil, :class => 'role_label'%>
					<%= label_tag @current_user.name, nil, :class => 'username_label'%>
				</div>
				<% else %>
				<% if @current_user.role? :department_header	%>
				<div id="nav_wrap">
					<ul>
						<li class="li_overview">
							<%= link_to "Overview", overview_department_path %>
						</li>
						<li class="li_activity">
							<%= link_to "Activity", activities_path %>
						</li>
						<li class="li_task">
							<%= link_to "Task", tasks_path %>
						</li>
						<li class="li_task_type">
							<%= link_to "Task Type", task_types_path %>
						</li>
						<li class="li_report">
							<%= link_to "Report", report_path %>
						</li>
					</ul>
					<%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class=>'sign_out' %>
					<%= label_tag '(' + @current_user.roles.first.name + ')', nil, :class => 'role_label'%>
					<%= label_tag @current_user.name, nil, :class => 'username_label'%>
				</div>
				<% else%>
				<% if @current_user.role? :staff %>
				<div id="nav_wrap">
					<%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class=>'sign_out' %>
					<%= label_tag '(' + @current_user.roles.first.name + ')', nil, :class => 'role_label'%>
					<%= label_tag @current_user.name, nil, :class => 'username_label'%>
				</div>
				<%end %>
				<%end%>
				<%end%>
			
			<div class="content">
				<p class="notice">
					<%= notice %>
				</p>
				<p class="alert">
					<%= alert %>
				</p>
				<%= yield %>
			</div>
			<% end %>
		</div>
	</body>
</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Open task - Log in</title>
  <%= stylesheet_link_tag    "authentication" %>
  <%= stylesheet_link_tag "scaffolds" %>
  <%= javascript_include_tag "application" %>
  <%  javascript_include_tag "users/load_departments" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body class="body_login">
<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->
<div class="body-div">
<div id="logo_div">
	<%= link_to (image_tag ("logo_opentask.png")), root_url, :id=>"img_logo" %>
</div>

<%= yield %>
</div>
</body>
</html>